hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/arsenal.pw.toml"
hash = "3dfb613d8cb47b4f9090d8eff4d67b94a62ca397a6e2bc27aee8fe96d6d264f7"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "bee459c3b3739a46717f04675ba175d8a5d26fc00a8683acd4ef5bdfb73a9066"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "2f57caef93731338be19b1e14065978eb3e14dbfc0c1f9699dfcc2f201e2c23b"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0ed502ad7d53ca1936079cb7508b2e085909610ac51337fff2a3ce0fa6dcae28"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "f460d01d0351226ce596672936cc09364028046e87fc357bd0218c6df3e89d83"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "429284603e4c5ca44777cb4ce2455477fcc1eee4dc9a4ae2f759c4895bf332e7"
metafile = true

[[files]]
file = "mods/cosmetic-armor.pw.toml"
hash = "195105e5e989cd109d5f644b58eca2e06f9d487d80ea365fa42033675aac7ac7"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "ff674220aeb9395349903de7d40a1af1bbcbc0aa9182c193df50b21225065709"
metafile = true

[[files]]
file = "mods/create-coggle.pw.toml"
hash = "5718996e966f1bf709a834b686913cd7b043de1f72293d24478c1b3289663afb"
metafile = true

[[files]]
file = "mods/create-curios-jetpack.pw.toml"
hash = "cec4725a97279fbfb332d072ff3d4f70e6f893f3c2ad74ad745f211b62e868ec"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "023532063fbf310dd047a33cf1afd06b0c4baf72da4dc23e78d1d599ad5dcccd"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric-restitched.pw.toml"
hash = "526bc4d124da6cb1c68d0164ec88cf0dcf355fa95cf6b465232d4955c9248196"
metafile = true

[[files]]
file = "mods/create-dreams-and-desires.pw.toml"
hash = "fd2c9cdc0083b93038ce74132c66078e8e223722c4fae902ba4bfef28c37ed71"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric-legacy.pw.toml"
hash = "46b9b7da92baae101a078a791500eb8d7b54255d882611be17b03085abe3d7b3"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "5265e90f91a651c018b78641d08442da55c060ce07a020afdf86bb79d12bbe8d"
metafile = true

[[files]]
file = "mods/create-molten-metals.pw.toml"
hash = "a148e2a84e91d4cc086911492305fd22dd512dab17fe92bf35c028d7ba6b3cc5"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "2c65b7ed826a2d147f0eb4788152b9f1ae878e0df102af58a9ea23ebd1c48f04"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "964a56ef500d320801315eb45687e51e9352f03615506469979875d2fed41760"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
hash = "916c17614ec51da73e173b7249118b473e479c370a48378bc7f91eb5e5abfa9d"
metafile = true

[[files]]
file = "mods/create-threaded-trains.pw.toml"
hash = "a171827ca41197cfe596f6624bdf574cbbc6532642c1f4dfd5a9d84de908e4b1"
metafile = true

[[files]]
file = "mods/escalated.pw.toml"
hash = "87ea98128e3482a772b346128930ba706c11f329770ddbd26ec11e08b0e306a2"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
hash = "18b0d44213fd3c7e22748e4ad775e6ce5cf243f9b38294130a826c845ae913c4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "e09385ac1a1c0900b8fa619290eb0f0539949ebbc59f7604a7699485784ccc85"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "fcfd264784dcda039d9efc0b3e47ef1f04521698761a34d2f20379d5f9c0fe26"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "f6629a3c5e023a96cb5d78d66e93b47245996c46a079921b3f6a6094209dc1b0"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
hash = "e7618fe94cbf0b7ea032e45cb448ab8151773ef71adb6dda8becd4d2fcc4dab5"
metafile = true

[[files]]
file = "mods/hexal.pw.toml"
hash = "3e51d9ad93efb292181f8960816a58707ae28841c310b77c28721ac7039931d1"
metafile = true

[[files]]
file = "mods/hextrogen.pw.toml"
hash = "ac621c9e11a24673d084bd94ff105500eb5038b1390668a8da21657fd30b3157"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
hash = "77705ea58913cad0baa1964f8ba1a37b2fdf640b955a70f4bc1ad985cdd14a5f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/maintenancemode.pw.toml"
hash = "be97476a17c343a9e5c2b5ba2616ed77b134777ceb23fa40940abd42acc128c2"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "200d34b575b506ab0503f7856cdcd4cc38030c27e0749e36f6bbe62cbeb16cec"
metafile = true

[[files]]
file = "mods/moreiotas.pw.toml"
hash = "6757363eeff33967a7beb9782d833cd9f23486933a88373e576a3856fbbaf1bd"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89ed99a0798a5e1300434359762c968536593279493f68b321a565fb1343f75c"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
hash = "49ef3ff0a74c6338f2160c4ee683ae34f745a38c0c87f2d7527e4f88406113fe"
metafile = true

[[files]]
file = "mods/ratatouille.pw.toml"
hash = "db7c47fac84cfc274fcb3ca5d86c2fa974dff11f81c6d7619d69cab59bf6fc99"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "3f9e020fb15e1c2ede36d50b40c72d536f6de3f817bd703d26805a747175c8bc"
metafile = true

[[files]]
file = "mods/roundabout_the_jojo_mod.pw.toml"
hash = "4255c1671a511b11bd9ec0d101b12c3c8a6e0d9cd2504af06ab0b0466206aa62"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "fae2bc6c282159f6a2e55e22d19241c625a9795dddbe8bd0f0b501c8aa709be1"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "47493d398295964924d386d0fb866dac1a2d5e0cd4692b8436ea2552ce6c99f6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "5cd3420078c7c24bf7414c7243a69b2d2a21c3c5e29150444697b11a001c44d8"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "021d42f729c7fba0ddca97369323325002ecb8437e2948d82478e682bb340e58"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "c709708a11f117743c086f16de67701eb35bfad331826960398bb1e64ea4d35f"
metafile = true
