hash-format = "sha256"

[[files]]
file = "mods/antique-atlas-4.pw.toml"
hash = "26860b6d05d186edfa64ca3c894c853e749b390d49bb4276f290535518aee08b"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/armorhide.pw.toml"
hash = "f33da29ad65ee4178827e844b93c72eec79bf22f93798ba439c3516ae8a65121"
metafile = true

[[files]]
file = "mods/arsenal.pw.toml"
hash = "3dfb613d8cb47b4f9090d8eff4d67b94a62ca397a6e2bc27aee8fe96d6d264f7"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "bee459c3b3739a46717f04675ba175d8a5d26fc00a8683acd4ef5bdfb73a9066"
metafile = true

[[files]]
file = "mods/better-end-cities-base.pw.toml"
hash = "2c05589983f4432f7f2f540bc9f38a030b21f2424dba577d6a8df68fd56a662a"
metafile = true

[[files]]
file = "mods/better-end-sky.pw.toml"
hash = "ef2ba75fd7e904270d2f9396cdda74ee34e91821f2a4ec0074ad98371b120385"
metafile = true

[[files]]
file = "mods/bl4cks-sit.pw.toml"
hash = "92b54fed693e725faa96e793b643cb5245494643830f2a4e277d6c7150368e7d"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "2f57caef93731338be19b1e14065978eb3e14dbfc0c1f9699dfcc2f201e2c23b"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "64a244469b7ce7be7e6ceabedd69d17e573a0b92d6e29c661fc6c490afa965d8"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0ed502ad7d53ca1936079cb7508b2e085909610ac51337fff2a3ce0fa6dcae28"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "f460d01d0351226ce596672936cc09364028046e87fc357bd0218c6df3e89d83"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "429284603e4c5ca44777cb4ce2455477fcc1eee4dc9a4ae2f759c4895bf332e7"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "ff674220aeb9395349903de7d40a1af1bbcbc0aa9182c193df50b21225065709"
metafile = true

[[files]]
file = "mods/create-clockwork.pw.toml"
hash = "ce13b5e51405cbfd8025a38dcbc707428566f820c3c1c98473507db0f4386007"
metafile = true

[[files]]
file = "mods/create-curios-jetpack.pw.toml"
hash = "cec4725a97279fbfb332d072ff3d4f70e6f893f3c2ad74ad745f211b62e868ec"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "023532063fbf310dd047a33cf1afd06b0c4baf72da4dc23e78d1d599ad5dcccd"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric-restitched.pw.toml"
hash = "526bc4d124da6cb1c68d0164ec88cf0dcf355fa95cf6b465232d4955c9248196"
metafile = true

[[files]]
file = "mods/create-dreams-and-desires.pw.toml"
hash = "fd2c9cdc0083b93038ce74132c66078e8e223722c4fae902ba4bfef28c37ed71"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric-legacy.pw.toml"
hash = "46b9b7da92baae101a078a791500eb8d7b54255d882611be17b03085abe3d7b3"
metafile = true

[[files]]
file = "mods/create-fabric-5-1-j-patch3.pw.toml"
hash = "143a1f23461d64c2eddd3c493ecf99159ba5fb88744bdcfc4bc3bf8441d1b972"
metafile = true

[[files]]
file = "mods/create-few-more-recipes.pw.toml"
hash = "54b45e4aa08c0b36a490face457abe090243d9190e622817e62be6e45353fb30"
metafile = true

[[files]]
file = "mods/create-molten-metals.pw.toml"
hash = "a148e2a84e91d4cc086911492305fd22dd512dab17fe92bf35c028d7ba6b3cc5"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "2c65b7ed826a2d147f0eb4788152b9f1ae878e0df102af58a9ea23ebd1c48f04"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "3520554d27d3bc697a9bdb515743241171a1f01fbbf4093f0a85e5385340e9a0"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
hash = "916c17614ec51da73e173b7249118b473e479c370a48378bc7f91eb5e5abfa9d"
metafile = true

[[files]]
file = "mods/create-threaded-trains.pw.toml"
hash = "a171827ca41197cfe596f6624bdf574cbbc6532642c1f4dfd5a9d84de908e4b1"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "c5ea75feae4d340856611f78a29e6f1f0b7e707bfe43847f11d25fac1769dee7"
metafile = true

[[files]]
file = "mods/distraction-free-recipes.pw.toml"
hash = "20fdb4bb9c30b2aa81499f43657c266e3d84fdb4a3b167c7fdbf3309e4316fc7"
metafile = true

[[files]]
file = "mods/escalated.pw.toml"
hash = "66aafe5f3151de3f2de0d7aabaecdcc2dfd6f5b59d0ea697002037dcea9e086e"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
hash = "18b0d44213fd3c7e22748e4ad775e6ce5cf243f9b38294130a826c845ae913c4"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "91dab84ae147fd26d1b61456329b78e76ef4109c21ecf9f96b6f967618079ab7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-custom-names.pw.toml"
hash = "c304e2cee42cba047bff6edace22c0929c495052bf9db0ca17abbc1e36d433a7"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/faithful-mace.pw.toml"
hash = "98ebe8a1988553c5d6d0d9b76016c15e90b605083a6e0dd1074eb3b2f78a9ae8"
metafile = true

[[files]]
file = "mods/farmers-cutting-regions-unexplored.pw.toml"
hash = "436183746bfcc03beb0fcfd469f220283352c1c8d084dc4563a95d8ca107fed0"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "e09385ac1a1c0900b8fa619290eb0f0539949ebbc59f7604a7699485784ccc85"
metafile = true

[[files]]
file = "mods/fastback.pw.toml"
hash = "5af15318e5df9f6dbaea6ee97d361b9acdb2c2f736cba315b08e10df7b0157db"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "fcfd264784dcda039d9efc0b3e47ef1f04521698761a34d2f20379d5f9c0fe26"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "493ed95320ee3cc9c2def86b9d0971c2ca4bb4215921c2a11208bee77d5dbfb5"
metafile = true

[[files]]
file = "mods/gravestones-fix.pw.toml"
hash = "9cc5869f09f90c5f3af001135dc1dedbcdbeccd6f01a6c59cdee2b53afe2f4d5"
metafile = true

[[files]]
file = "mods/gravestones.pw.toml"
hash = "e02e297f397621e1c0d17f6853d5176e23343609e978ac3fd35f1a73d00d509c"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "f6629a3c5e023a96cb5d78d66e93b47245996c46a079921b3f6a6094209dc1b0"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
hash = "e7618fe94cbf0b7ea032e45cb448ab8151773ef71adb6dda8becd4d2fcc4dab5"
metafile = true

[[files]]
file = "mods/hexal.pw.toml"
hash = "3e51d9ad93efb292181f8960816a58707ae28841c310b77c28721ac7039931d1"
metafile = true

[[files]]
file = "mods/hextrogen.pw.toml"
hash = "ac621c9e11a24673d084bd94ff105500eb5038b1390668a8da21657fd30b3157"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
hash = "77705ea58913cad0baa1964f8ba1a37b2fdf640b955a70f4bc1ad985cdd14a5f"
metafile = true

[[files]]
file = "mods/interactive.pw.toml"
hash = "d35c75ec92d4e1c46d264d41685bf261b5984d81457762bd5f360e4fce251261"
metafile = true

[[files]]
file = "mods/iris-flw-compat.pw.toml"
hash = "8619be4a2d5da2deff6cee6ebda356c1a7fdf3a36d8b58d31cd6ddd5b1649ca1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b023a335aa5ebb14048587cfef85b374c023518a1db303eb24f1175530ab0085"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "9495bb2388d7fa5ccf6b33b485f75c7ed15f8a59956406a92ad427e8504980e8"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "d6be91dc0a2aca23ee640818d8a8295c85ddb2db6e0413669ecac9600b01eef0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "fa99f0e912a4e109d1f5714bfc4a31a152dd78e97ed6fc392a38d62ec52f5f23"
metafile = true

[[files]]
file = "mods/maintenancemode.pw.toml"
hash = "be97476a17c343a9e5c2b5ba2616ed77b134777ceb23fa40940abd42acc128c2"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "200d34b575b506ab0503f7856cdcd4cc38030c27e0749e36f6bbe62cbeb16cec"
metafile = true

[[files]]
file = "mods/moreiotas.pw.toml"
hash = "6757363eeff33967a7beb9782d833cd9f23486933a88373e576a3856fbbaf1bd"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/moyai.pw.toml"
hash = "8a80af48bb06e3fd000fc6c3f222877a9995769ae1e1aa58f48325290fbede4d"
metafile = true

[[files]]
file = "mods/mystical-oak-tree.pw.toml"
hash = "77b1b462c5717cf66d59f9a1a906b6afb526488a7d16c109082d4a64b1e4967d"
metafile = true

[[files]]
file = "mods/new-lodestone-recipe.pw.toml"
hash = "6e0e0ebc0b2ef8ec339f9d7b658fb7403c00a787d481469e881a407b9b2a9a74"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89ed99a0798a5e1300434359762c968536593279493f68b321a565fb1343f75c"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "e5e76b305f6e8fd611fb70695f42014c62e5f46b926d626eaf5ca0c78e394c5c"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
hash = "49ef3ff0a74c6338f2160c4ee683ae34f745a38c0c87f2d7527e4f88406113fe"
metafile = true

[[files]]
file = "mods/player-locator-plus.pw.toml"
hash = "7bb62be8c97ff5bad23337b066a4d1f491226cd840be3cc10489480312dd9eb9"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a1eff7b33a54586b6989c7bfd89992f9d315f1c656b7596649d9af7017c6af7b"
metafile = true

[[files]]
file = "mods/ratatouille.pw.toml"
hash = "db7c47fac84cfc274fcb3ca5d86c2fa974dff11f81c6d7619d69cab59bf6fc99"
metafile = true

[[files]]
file = "mods/regions-unexplored.pw.toml"
hash = "1dec5eab016f2b91c2b4c39cb6d0c3f9c9e0f41de359670e9518078dd788240f"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "3f9e020fb15e1c2ede36d50b40c72d536f6de3f817bd703d26805a747175c8bc"
metafile = true

[[files]]
file = "mods/roundabout_the_jojo_mod.pw.toml"
hash = "4255c1671a511b11bd9ec0d101b12c3c8a6e0d9cd2504af06ab0b0466206aa62"
metafile = true

[[files]]
file = "mods/scout.pw.toml"
hash = "6fa55fab0c5c22dc7092891f2128d3a0e718d78ad53fa8082af3cfc6e850526a"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "3070e7a9aa7244e36fdb27a904ac7433ed4d119336977d1837f486f60724a9b1"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "47493d398295964924d386d0fb866dac1a2d5e0cd4692b8436ea2552ce6c99f6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "5cd3420078c7c24bf7414c7243a69b2d2a21c3c5e29150444697b11a001c44d8"
metafile = true

[[files]]
file = "mods/spawn-mod.pw.toml"
hash = "84278fdbdb9345a1fe943b4b62437c2f3b17b489c4edfa078b4d0f71d16e5831"
metafile = true

[[files]]
file = "mods/surveyor.pw.toml"
hash = "f05a1d7a46d6844e139a23b46be8fa214f0029a1a9c202689e98e9f7fb67ac05"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "ce8868bbecfc78d470fe88663e4128751a4282968adaa5e5676544ecabab6355"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "b3ae602303fd717bff2344bfb89aa427e2b4a1ab5fffdcc25183b22102c492df"
metafile = true

[[files]]
file = "mods/tick-stasis.pw.toml"
hash = "08f7763d759fb7778ae0560e8adf66e4721fc6d9e46802f51ecced02716bdef3"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
hash = "3f12e299c61128e9b68e30f814a8507437afc84e27c678fe7955ced741fc176a"
metafile = true

[[files]]
file = "mods/valkyrien-skies-old.pw.toml"
hash = "f3e12c09b722448ec38c9ad1bec1d4c5a24b99bdd69b5ca7c33173d53bbc8c3c"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "a9b241cbbff036293ceb73c9fac0f58c2b1d60cefb2aed0212fc936556a16df8"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "c709708a11f117743c086f16de67701eb35bfad331826960398bb1e64ea4d35f"
metafile = true
