name = "Main Modded Server Pack Latest"
author = "Jeb_Kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af82c743e4d4c63bf2ca0c9dae1045db81c5cb9e3b01248a3d448a22dd1e9dce"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
