name = "Main Modded Server Pack Latest"
author = "Jeb_Kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "051794d1c0553578164d9e15f8a2944f0a8e911816663de71014bd5f706b88cb"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
