name = "Main Modded Server Pack Latest"
author = "Jeb_Kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e025daa9077bed3893ee00e508ceb40dd0ef0d78e4b25817bde02e338c7643b"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
