name = "Main Modded Server Pack Latest"
author = "Jeb_Kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49c92d51c1a8052757747600a1c51b730556cb27ec5f83b4fc192afb0f7767f1"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
