name = "Main Modded Server Pack Latest"
author = "Jeb_Kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4086071900ac1ca3973354526e3ce890a7f10768c9d49cd98cb490e67cbd6933"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
