name = "Main Modded Server Pack Latest"
author = "Jeb_Kerm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f248dd846ec2632917d69d2c009c6222113dae6bc1d66659888aa2ad648c083"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
