hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/arsenal.pw.toml"
hash = "3dfb613d8cb47b4f9090d8eff4d67b94a62ca397a6e2bc27aee8fe96d6d264f7"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
hash = "ab1e22cc66189067e002a204c70c553cc7cc0e738bd602f405d7cc37561260be"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
hash = "dd8057c40ff94e9a21a121583884f71c9a6b1eaa6f913ef46c5d1f9b37fe487f"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "2f57caef93731338be19b1e14065978eb3e14dbfc0c1f9699dfcc2f201e2c23b"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "127f0a7311e4ecd77c0b96660e0ff873d78d253fffb68db6101eeb414de38bb1"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/comfortable-campfires.pw.toml"
hash = "3e5d790034d773c643ec98aed8a5d52101e56d4851c4cf776334e3a032ad5bf2"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "2245beed2b8b7f2be3cb3b50528693fd1a307ba758aa9a80239510c2e26194ab"
metafile = true

[[files]]
file = "mods/create-curios-jetpack.pw.toml"
hash = "7469476f6992f6d3b976e234146e7358975b74d93136ff20a6baaf45fb4db382"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "023532063fbf310dd047a33cf1afd06b0c4baf72da4dc23e78d1d599ad5dcccd"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric-restitched.pw.toml"
hash = "b5f041fe191a671a44452a71f27d27be6a630e4db80dc1ac96ed72e8dd6daa4c"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "7d227ef90b1918ceb348ade235a5d17c7894acbf387575e96c08920a5bad1bbb"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
hash = "916c17614ec51da73e173b7249118b473e479c370a48378bc7f91eb5e5abfa9d"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "c92aae37a2b79c96ac72e17695d1bcbdc35ca51d56f0fb8d1d9ffa9dace45274"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
hash = "3f352f4d2bd17152dc5d39010fb409c75f84e8ae9d8fd0d5da1e331b60e01999"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "8697b0c71170d6e9bc4c30726581a63ad0ff9b15dbc810e295169234a6a0849e"
metafile = true

[[files]]
file = "mods/enchancement.pw.toml"
hash = "54ed85b42559773c1d59f774b7d1e17938232b97432b20469ead70d69673b6ab"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "e286c31c1b559e037730992bdc995383f6e783baa7b8c6c625e52c48a509d8b0"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
hash = "18b0d44213fd3c7e22748e4ad775e6ce5cf243f9b38294130a826c845ae913c4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2d44be0de504bd05e2f6f2e4644f5d7afd2401adcdff92c19871db204e121988"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "97e7fb0bf5c563366b7c6121fa2decb67597107e5594932c6a098cccc980629e"
metafile = true

[[files]]
file = "mods/faithful-mace.pw.toml"
hash = "3eec11fa505d4472119cdf8fb6109369a1b4c484cba5a6907de885aaea0037d5"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "63816a982df44357b787c041f281e3ee3bb86768493e6e043aa38b99d3c2ea57"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "4449401b59481016fa2a66d6e749795129160cb1ab3e7932e15033c6b5815455"
metafile = true

[[files]]
file = "mods/goggle-trinket-slot.pw.toml"
hash = "3d0c54755d5bcd0b8e306bd1ac9d648bef47e72dffa4ff8de20237e29162691e"
metafile = true

[[files]]
file = "mods/gravity-api-fork.pw.toml"
hash = "4744eec2487b3cc307ceaa93d1a1c021d06d3734da513437558701a737797e85"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
hash = "61e5f0c2fc067877744d9cdbed9704e4da4933a4be893e5ef61174346fb13af6"
metafile = true

[[files]]
file = "mods/hexcassettes.pw.toml"
hash = "39e27b12d6b188df2b249bf84ed8427c62a7d9c9802ab0469304d554f89f43be"
metafile = true

[[files]]
file = "mods/hexical.pw.toml"
hash = "353bc9603d4bfa25ce7e2e15a1a8cf34f6ab18695cdafd8c4e0d351e841ac157"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/infernum-effugium.pw.toml"
hash = "a7abc895474e1851bcb4957e69d6d9fdef3411b7ee989932e1673e109622f5a6"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "4b2d106ce00d09612a66ced11538304eedc540267a285976da54da8f2f624eb2"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d7cf7b5f76fdd8f9c63a95c9d82bce7162321232675b53d7b54aebaf537d70e0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a08a445002542d96a8481654c3f4b5e2d3c064f77b477aeaa3a1d1c3cd396ca8"
metafile = true

[[files]]
file = "mods/maintenancemode.pw.toml"
hash = "be97476a17c343a9e5c2b5ba2616ed77b134777ceb23fa40940abd42acc128c2"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "b7a5102d9c5e8b022ea507d219520130ebfefd0eeddfd74c3627aa6f27335932"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "e94cfc8b72a467d63c5d7593a433edaf698a3792e0c9b95274751ba6d8435288"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
hash = "49ef3ff0a74c6338f2160c4ee683ae34f745a38c0c87f2d7527e4f88406113fe"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "e7aaef7215f2419177f1b1d3240d2d61d17ca2b2e03127d92941874ad5594d6f"
metafile = true

[[files]]
file = "mods/ratatouille.pw.toml"
hash = "db7c47fac84cfc274fcb3ca5d86c2fa974dff11f81c6d7619d69cab59bf6fc99"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "77a658a9d9cec5037136b95c42d1dff26dbf4010f17ecb2116bebf69178a03ba"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "3f9e020fb15e1c2ede36d50b40c72d536f6de3f817bd703d26805a747175c8bc"
metafile = true

[[files]]
file = "mods/reusable-trims.pw.toml"
hash = "a54097f6e7b3b6bc73a7e35b69fdf2d43008fbdf4d1a1db861f5d8dcd7c38762"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "b7300bbf22cad6c99e2a4922ec7cee7564d59c976b7895884b6a5f0f1ae8bcb6"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "8b0a4f165bfb20db28433ff27a49a9998fb4fb9b09d4a6bb68bc0e0983b80bec"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "b52762ecbf8d003dcfece87414708d94db789a01d98cae1530464f2906a958f2"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ee103bf45111c2cd7ea2d9b31087867dd4b0d07a4b7dad7b138a4ae506127b37"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "c28f21e5e16aa98001e982453e1b2b8f99302497c645bca4a02a708cfc16577d"
metafile = true
